/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epic.ipg.util.varlist;

/**
 *
 * @author chanuka_g
 */
public class QueryVarList {

    private QueryVarList() {
    }

    public static final String SELECT_CUSTOMER_TXN_COUNT = " SELECT COUNT(t.IPGTRANSACTIONID) AS TXNCOUNT  FROM IPGTRANSACTION t, IPGMERCHANT m, IPGCARDASSOCIATION c,IPGSTATUS s  "
            + " WHERE  t.MERCHANTID=m.MERCHANTID AND t.CARDASSOCIATIONCODE=c.CARDASSOCIATIONCODE AND t.STATUSCODE=s.STATUSCODE AND t.CREATEDTIME >= to_date(?, 'yy-mm-dd') AND  t.CARDHOLDERPAN LIKE ? AND  s.DESCRIPTION LIKE ? ORDER BY t.IPGTRANSACTIONID DESC ";

    public static final String SELECT_CUSTOMER_TXN_DETAIL
            = " SELECT t.IPGTRANSACTIONID, m.merchantname, c.DESCRIPTION AS CARDASSOCIATION, t.CARDHOLDERPAN, t.AMOUNT, t.MERCHANTID, s.description AS STATUS, t.CREATEDTIME  FROM IPGTRANSACTION t, IPGMERCHANT m, IPGCARDASSOCIATION c,IPGSTATUS s  "
            + " WHERE  t.MERCHANTID=m.MERCHANTID AND t.CARDASSOCIATIONCODE=c.CARDASSOCIATIONCODE AND t.STATUSCODE=s.STATUSCODE AND "
            + " t.CREATEDTIME >= to_date(?, 'yy-mm-dd') AND  t.CARDHOLDERPAN LIKE ? AND  s.DESCRIPTION LIKE ? ORDER BY t.IPGTRANSACTIONID DESC ";

    public static final String SELECT_MERCHANT_TXN_COUNT = " SELECT COUNT(t.IPGTRANSACTIONID) AS TXNCOUNT  FROM IPGTRANSACTION t, IPGMERCHANT m, IPGCARDASSOCIATION c,IPGSTATUS s  "
            + " WHERE  t.MERCHANTID=m.MERCHANTID AND t.CARDASSOCIATIONCODE=c.CARDASSOCIATIONCODE AND t.STATUSCODE=s.STATUSCODE AND t.CREATEDTIME >= to_date(?, 'yy-mm-dd') AND  t.MERCHANTID LIKE ? AND  s.DESCRIPTION LIKE ? ORDER BY t.IPGTRANSACTIONID DESC ";

    public static final String SELECT_MERCHANT_TXN_DETAIL = " SELECT t.IPGTRANSACTIONID, m.merchantname, c.DESCRIPTION AS CARDASSOCIATION, t.CARDHOLDERPAN, t.AMOUNT,t.MERCHANTID,"
            + " s.description AS STATUS, t.CREATEDTIME  FROM IPGTRANSACTION t, IPGMERCHANT m, IPGCARDASSOCIATION c,IPGSTATUS s  "
            + " WHERE  t.MERCHANTID=m.MERCHANTID AND t.CARDASSOCIATIONCODE=c.CARDASSOCIATIONCODE AND t.STATUSCODE=s.STATUSCODE AND "
            + " t.CREATEDTIME >= to_date(?, 'yy-mm-dd') AND  t.MERCHANTID LIKE ? AND  s.DESCRIPTION LIKE ? ORDER BY t.IPGTRANSACTIONID DESC ";

    public static final String SELECT_TXN_INITIATE_STATUS = "SELECT HM.TRANSACTIONINITAIATEDSTATUS "
            + "FROM IPGMERCHANT m ,IPGHEADMERCHANT hm "
            + "WHERE "
            + "m.MERCHANTID = ? "
            + "and HM.MERCHANTCUSTOMERID = M.MERCHANTCUSTOMERID ";

    public static final String SELECT_BATCH_NUMBER = "SELECT b.BATCHNUMBER FROM IPGBATCH b WHERE b.MERCHANTID=? AND b.STATUS=?";

    public static final String SELECT_CUSTOMER_EMAIL = "SELECT T.CARDHOLDEREMAIL FROM IPGTRANSACTION T WHERE T.IPGTRANSACTIONID = ? ";

    public static final String SELECT_DAILY_TXN_AMOUNT = "SELECT nvl(SUM(AMOUNT),0) AS TOTALAMOUNT FROM IPGTRANSACTION WHERE MERCHANTID = ? "
            + "AND TRUNC(TRANSACTIONCREATEDDATETIME) = TO_DATE(? , 'DD-MON-RR') AND STATUSCODE IN(?,?,?,?)";

    public static final String SELECT_DAILY_TXN_COUNT = "SELECT COUNT(IPGTRANSACTIONID) AS TXNCOUNT FROM IPGTRANSACTION WHERE "
            + "MERCHANTID = ? AND TRUNC(TRANSACTIONCREATEDDATETIME) = TO_DATE(? , 'DD-MON-RR') AND STATUSCODE IN(?,?,?,?)";

    public static final String SELECT_MERCHANT_RISK_PROFILE = "SELECT r.RISKPROFILECODE,r.MAXIMUMSINGLETXNLIMIT,r.MAXIMUMTXNCOUNT,r.MINIMUMSINGLETXNLIMIT,"
            + " r.MAXIMUMTOTALTXNAMOUNT,m.COUNTRYCODE FROM IPGRISKPROFILE r, IPGMERCHANT m "
            + "WHERE m.MERCHANTID = ? and m.RISKPROFILECODE = r.RISKPROFILECODE";

    public static final String SELECT_MERCHANT_CUSTOMER_RISK_PROFILE = "SELECT "
            + "r.RISKPROFILECODE,r.MAXIMUMSINGLETXNLIMIT, "
            + "r.MAXIMUMTXNCOUNT,r.MINIMUMSINGLETXNLIMIT, "
            + "r.MAXIMUMTOTALTXNAMOUNT,m.COUNTRYCODE "
            + "FROM IPGRISKPROFILE r, "
            + "IPGMERCHANT m "
            + "WHERE "
            + "m.MERCHANTID = ? "
            + "and r.RISKPROFILECODE = m.RISKPROFILECODE ";

    public static final String SELECT_BLOCKED_BIN = "SELECT BIN FROM IPGRISKPROFILEBLOCKEDBIN WHERE RISKPROFILECODE = ? ";

    public static final String SELECT_BLOCKED_COUNTRY = "SELECT COUNTRYCODE FROM IPGRISKPROFILEBLOCKEDCOUNTRY WHERE RISKPROFILECODE = ? ";

    public static final String SELECT_BLOCKED_CURRENCY = "SELECT CURRENCYCODE FROM IPGRISKPROFILEBLOCKEDCURRENCY WHERE RISKPROFILECODE = ? ";

    public static final String SELECT_BLOCKED_MCC = "SELECT MCCCODE FROM IPGRISKPROFILEBLOCKEDMCC WHERE RISKPROFILECODE = ?";

    public static final String SELECT_RULES_IPG_LEVEL = " SELECT I.RULEID, I.RULESCOPECODE, I.OPERATOR, I.RULETYPECODE, I.STARTVALUE, I.ENDVALUE, I.TRIGGERSEQUENCEID FROM IPGRULE I "
            + " WHERE "
            + " I.TRIGGERSEQUENCEID = ? AND "
            + " I.SECURITYLEVEL = ? ";

    public static final String SELECT_RULES_MERCHANT_LEVEL = " SELECT I.RULEID, I.RULESCOPECODE, I.OPERATOR, I.RULETYPECODE, I.STARTVALUE, I.ENDVALUE, I.TRIGGERSEQUENCEID FROM IPGRULE I, IPGMERCHANTRULE M "
            + " WHERE "
            + " I.RULEID = M.RULEID AND "
            + " M.MERCHANTID = ? AND "
            + " I.TRIGGERSEQUENCEID = ? AND "
            + " I.SECURITYLEVEL = ? ";

    public static final String SELECT_3DSECURE_ENABLE_STATUS = " SELECT M.AUTHENTICATIONREQUIED FROM IPGMERCHANT M "
            + " WHERE M.MERCHANTID = ?";

    public static final String SELECT_TRANSACTION_DATA = " SELECT t.IPGTRANSACTIONID, m.merchantname, c.DESCRIPTION AS CARDASSOCIATION, t.CARDHOLDERPAN, t.AMOUNT,t.MERCHANTID,"
            + " s.description AS STATUS, t.CREATEDTIME  FROM IPGTRANSACTION t, IPGMERCHANT m, IPGCARDASSOCIATION c,IPGSTATUS s WHERE  t.MERCHANTID=m.MERCHANTID AND t.CARDASSOCIATIONCODE=c.CARDASSOCIATIONCODE AND t.STATUSCODE=s.STATUSCODE "
            + " AND t.IPGTRANSACTIONID = ? ";

    public static final String SELECT_MERCHANT_BY_TXN = "select IPGMERCHANT.PRIMARYURL, "//0
            + "IPGMERCHANT.SECONDARYURL, "//1
            + "IPGTRANSACTION.MERCHANTREFERANCENO, "//2
            + "IPGTRANSACTION.MERCHANTID, "//3
            + "IPGMERCHANT.DINAMICRETURNSUCCESSURL, "//4
            + "IPGMERCHANT.DINAMICRETURNERRORURL, "//5
            + "IPGTRANSACTION.LASTUPDATEDTIME, "//6
            + "IPGTRANSACTION.AMOUNT, "//7
            + "CURRENCY.CURRENCYCODE CURRENCYCODE "//8
            + "FROM IPGMERCHANT,IPGTRANSACTION "
            + "LEFT OUTER JOIN IPGCURRENCY CURRENCY ON CURRENCY.CURRENCYISOCODE = IPGTRANSACTION.CURRENCYCODE "
            + "WHERE IPGTRANSACTION.IPGTRANSACTIONID=? AND "
            + "IPGTRANSACTION.MERCHANTID =IPGMERCHANT.MERCHANTID ";

    public static final String INSERT_3DSECURE_VEREQ = " INSERT INTO IPG3DSECUREVERIFICATIONREQUEST ("
            + " IPGTRANSACTIONID, "
            + " CARDHOLDERPAN, "
            + " ACQUIRERBIN, "
            + " MERCHANTID, "
            + " MERCHANTNAME, "
            + " COUNTRYCODE, "
            + " PURCHASEDATETIME, "
            + " AMOUNT, "
            + " CURRENCY, "
            + " EXPONENT, "
            + " PASSWORD, "
            + " CARDEXPIRYDATE, "
            + " DEVICECATEGORY, "
            + " ACCEPTHEADER, "
            + " USERAGENT, "
            + " MESSAGEEXTENTION, "
            + " ORDERDESCRIPTION, "
            + " LASTUPDATEDUSER "
            + " ) "
            + " VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";

    public static final String INSERT_3DSECURE_VERES = "INSERT INTO IPG3DSECUREVERIFICATIONRES ("
            + " IPGTRANSACTIONID, "
            + " ACCOUNTHOLDERAUTHENTICATIONVAL, "
            + " ECIVALUE, "
            + " LASTUPDATEDUSER "
            + " ) "
            + " VALUES(?, ?, ?, ?) ";

    public static final String INSERT_INITIAL_TRANSACTION = "INSERT INTO IPGTRANSACTION(IPGTRANSACTIONID, MERCHANTID,MERCHANTTYPE,TERMINALID,MERCHANTREMARKS,"
            + "CARDASSOCIATIONCODE,CARDHOLDERPAN,CURRENCYCODE,AMOUNT,"
            + "CARDNAME,EXPIRYDATE,CVCNUMBER,CVVNUMBER,CIDNUMBER,"
            + "STATUSCODE,BATCHNUMBER,MERCHANTREFERANCENO,COUNTRYCODE,CLIENTIP,LASTUPDATEDUSER,TRANSACTIONCREATEDDATETIME,"
            + "CARDHOLDEREMAIL,CARDHOLDERMOBILE,CARDHOLDERADDRESS,CARDHOLDERCITY,MASKING_CARD,TRANSACTIONCODE) "
            + " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";

    public static final String INSERT_TRANSACTION_HISTORY = " INSERT INTO IPGTRANSACTIONHISTORY(IPGTRANSACTIONID, STATUSCODE, REMARKS, ANALYTIME) "
            + " VALUES(?, ?, ?, ?) ";

    public static final String UPDATE_TRANSACTION_STATE = " UPDATE IPGTRANSACTION SET STATUSCODE = ?, LASTUPDATEDTIME = ? WHERE IPGTRANSACTIONID = ? ";

    public static final String UPDATE_TRANSACTION_STATE_3DSECURE_ENABLE = " UPDATE IPGTRANSACTION SET LASTUPDATEDTIME = ?, IS3DSECURE = ? WHERE IPGTRANSACTIONID = ? ";

    public static final String UPDATE_TRANSACTION_MPI_RES = " UPDATE IPGTRANSACTION "
            + " SET "
            + " STATUSCODE = ?, "
            + " CAVV = ?, "
            + " CVV = ?, "
            + " ECI = ?, "
            + " LASTUPDATEDTIME = ? "
            + " WHERE IPGTRANSACTIONID = ? ";

    public static final String SELECT_MERCHANT_ADDON = "SELECT m.MERCHANTID,m.LOGOPATH,m.XCORDINATE,m.YCORDINATE,"
            + "m.DISPLAYTEXT,m.THEMECOLOR,m.FONTFAMILY,m.FONTSTYLE,m.FONTSIZE,"
            + "m.REMARKS,m.LASTUPDATEDUSER,im.MERCHANTNAME,"
            + "m.LASTUPDATEDTIME,m.CREATEDTIME FROM IPGMERCHANTADDON m ,IPGMERCHANT im "
            + "WHERE m.MERCHANTID=im.MERCHANTID AND m.MERCHANTID=?";

    public static final String SELECT_MERCHANT_DETAIL = "select m.addressid, merchantname,m.contactperson,m.countrycode,m.createdtime,"
            + "m.dateofexpiry,m.dateofregistry,m.primaryurl,m.remarks,m.statuscode,"
            + "m.SECURITYMECHANISM,m.SYMETRICKEY,m.DINAMICRETURNERRORURL,m.merchantid,m.DINAMICRETURNSUCCESSURL "
            + "from ipgmerchant m  where m.merchantid=?";

    public static final String SELECT_SERVICE_CHARGE = "SELECT s.RATE,s.VALUE  FROM IPGMERCHANTSERVICECHARGE m,IPGSERVICECHARGE s "
            + "WHERE m.SERVICECHARGEID=s.SERVICECHARGEID AND m.MERCHANTID=?";

    public static final String SELECT_MERCHANAT_TERMINAL = "SELECT mc.TERMINALID FROM IPGMERCHNATTERMINAL MC WHERE mc.MERCHANTID=? AND "
            + "mc.CURRENCYTYPE=?";

    public static final String SELECT_MERCHANT_CREDENTIAL = "SELECT mc.password FROM IPGMERCHANTCREDENTIAL MC WHERE mc.merchantid=? AND "
            + "mc.cardassociationcode=?";

    public static final String SELECT_ALLOW_ECI = " SELECT I.STATUS FROM IPGAUTHCONFIGURATION I "
            + " WHERE I.CARDASSOCIATIONCODE = ? AND I.ECIVALUE=? AND I.TXSTATUS=?";

    public static final String SELECT_ECI_DATA = " SELECT I.ECI, I.CARDASSOCIATIONCODE FROM IPGTRANSACTION I "
            + " WHERE I.IPGTRANSACTIONID = ? ";

    public static final String SELECT_COMMON_CONFIG = "SELECT VALUE FROM IPGCOMMONCONFIG WHERE CODE=?";

    public static final String SELECT_CURRENCY_CODE = "SELECT C.CURRENCYCODE FROM IPGCURRENCY C WHERE C.CURRENCYISOCODE=?";

    public static final String SELECT_COMMON_FILEPATH = "SELECT TRANSACTIONLOG,INFOLOG,ERRORLOG,CERTIFICATES,CCBTXNFILES,IPGMERCHANLOGIN,"
            + "IPGRULEVALIDATION,IPGRISKVALIDATION,MPIREQUEST,MPIRESPONSE,SWITCHREQUEST,"
            + "SWITCHRESPONSE,KEYSTOREPATH,CERTPATH,KEYPATH FROM IPGCOMMONFILEPATH WHERE OSTYPE = ?";

    public static final String SELECT_DEFAULT_MERCHANT = "SELECT HM.TRANSACTIONINITAIATEDMERCHNTID FROM IPGMERCHANT m ,IPGHEADMERCHANT hm "
            + "WHERE m.MERCHANTID = ? and "
            + "HM.MERCHANTCUSTOMERID = m.MERCHANTCUSTOMERID ";

    public static final String SELECT_MERCHANT_ADDON_FIELDS = "SELECT AF.DESCRIPTION,AF.FIELDNAME,AF.FIELDSIZE FROM IPGMERCHANTADDONFIELDS MAF "
            + "LEFT OUTER JOIN IPGADDONFIELDS AF ON AF.FIELDID = MAF.FIELDID WHERE MERCHANTID = ?";

    public static final String SELECT_TRANSACTION_REQUEST_DATA = "SELECT T.IPGTRANSACTIONREQUESTID, T.MERCHANTID,T.CUSTOMERNAME,T.AMOUNT,T.EMAIL,T.CURRENCYCODE,C.CURRENCYCODE CURRENCY "
            + "FROM IPGTRANSACTIONREQUEST T LEFT OUTER JOIN IPGCURRENCY C ON C.CURRENCYISOCODE = T.CURRENCYCODE "
            + "WHERE  T.IPGTRANSACTIONREQUESTID = ? ";
}
